/** Declaration file generated by dts-gen */
declare module 'swig-templates' {
  export const version: string;

  export function Swig(opts: any): any;

  export function compile(source: any, options: any): any;

  export function compileFile(pathname: any, options: any, cb: any): any;

  export function invalidateCache(): void;

  export function parseFile(pathname: any, options: any): any;

  export function precompile(source: any, options: any): any;

  export function render(source: any, options: any): any;

  export function renderFile(pathName: any, locals: any, cb?: any): any;

  export function run(tpl: any, locals: any, filepath: any): any;

  export function setDefaultTZOffset(offset: any): void;

  export function setDefaults(options: any): void;

  export function setExtension(name: any, object: any): void;

  export function setFilter(name: any, method: any): void;

  export function setTag(name: any, parse: any, compile: any, ends: any, blockLevel: any): void;

  export namespace Swig {
    const prototype: {};
  }

  export namespace compile {
    const prototype: {};
  }

  export namespace compileFile {
    const prototype: {};
  }

  export namespace invalidateCache {
    const prototype: {};
  }

  export namespace loaders {
    function fs(basepath: any, encoding: any): any;

    function memory(mapping: any, basepath: any): any;

    namespace fs {
      const prototype: {};
    }

    namespace memory {
      const prototype: {};
    }
  }

  export namespace parseFile {
    const prototype: {};
  }

  export namespace precompile {
    const prototype: {};
  }

  export namespace render {
    const prototype: {};
  }

  export namespace renderFile {
    const prototype: {};
  }

  export namespace run {
    const prototype: {};
  }

  export namespace setDefaultTZOffset {
    const prototype: {};
  }

  export namespace setDefaults {
    const prototype: {};
  }

  export namespace setExtension {
    const prototype: {};
  }

  export namespace setFilter {
    const prototype: {};
  }

  export namespace setTag {
    const prototype: {};
  }
}
